### PR TITLE
Add location.reload(); when there is an error

### PR DESCRIPTION
**Pull request by gregory-yet**
At line 157 

``` javascript
popup("error", "Please login to continue farming...");
location.reload();
```

When we farming a lot, this error stop the farming, but if we reload the page, that work again, so if you add a "location.reload" this can be automatically ^^

Thanks

### CODE REVIEW

**Comment by demaisj** [comment]
Hello,
thank you for contributing.

Your idea is great, I forgot to implement this feature to the project.
In you pull request you forgot to add a reloading line to all errors, I'll create a commit by myself instead.

In contrary to your suggestion I will not add reloading to the "Please sign in" error since the user is not logged at this time, so he won't get any tickets. Maybe if someone is logging on another page than the farming page, I'll add a reloading.
The next problem is DDOS: csgoprizes is known for his "crappy" servers, on high traffic the farm can stop on a "high traffic" page. Reloading is convenient but I might add a delay on error before refreshing to avoid DDOS (even if the script is already "spamming" the servers when farming :D).

If you have any other suggestion please reply!

NOTE: You could have created an issue instead of a pull request since your changes were minor and this was more like a suggestion.

**Comment by gregory-yet** [comment]
Sorry, that was an error my pull request i never use this functionnality ^^

But when there is a popup with the "Please sign in", i'm already sign in, and if i reload the page, this works again so i don't understand why i have a popup with "please sign in" ^^
For the moment, i've add this location.reload() in the userscript, i wanted to create this issues on github for everyone who had this problem ;)

**Comment by demaisj** [comment]
Well your problem is pretty awkward... Can you give me more information about it ?
Actually the script is saying that you are not logged in when the "Login with Steam" button of the navbar is found on the DOM.
Do you sign in while farming? Or do you start farming before logging in?

**Comment by demaisj** [comment]
Hello,
it seems that I have encountered a similar problem as yours minutes ago. I was logged on the website, all of a sudden I wasn't logged in, and when I pressed refresh I was logged back. The csgoprizes/leagueprizes website is currently causing this issue, showing often the page as a non-logged user.

I'll add the reloading on "Please sign in error" in the 1.1 version.

Thank you for contributing!

**Pull request closed without merging**
